# Generated by Django 3.1.3 on 2020-12-03 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickUpUserId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(blank=True, max_length=64, verbose_name='Authorization token')),
                ('click_up_user_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='ClickUp User unique id')),
                ('team_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='ClickUp Team unique id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='click_up', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clickup_user_ids',
            },
        ),
    ]
